# Generated by Django 5.1.7 on 2025-04-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0002_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trainer_email", models.EmailField(max_length=254)),
                ("details", models.TextField()),
                ("video", models.FileField(upload_to="trainer_videos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
