# Generated by Django 5.1.7 on 2025-04-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0003_trainervideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("trainer_email", models.EmailField(max_length=254)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("username", "trainer_email")},
            },
        ),
    ]
